sudo: required 
dist: trusty 
language: generic 

cache:
  directories:
    - $HOME/.ccache

git:
  quiet: true

env:
  global:
    - CCACHE_DIR=$HOME/.ccache
    - ROS_REPO=ros
  matrix:
    - ROS_DISTRO="noetic"
    - ROS_DISTRO="noetic" ROS_REPO=ros-shadow-fixed UPSTREAM_WORKSPACE='github:simonschmeisser/industrial_core@noetic-compat'

matrix:
  allow_failures:
    - env: ROS_DISTRO="noetic" ROS_REPO=ros-shadow-fixed

install:
  - git clone --quiet --depth=1 https://github.com/ros-industrial/industrial_ci.git .ci_config

script: 
  - .ci_config/travis.sh
